#! /bin/bash
set -e

# Add users and groups
groupadd xroad-metrics || echo "Group 'xroad-metrics' not created as it already exists."
useradd --create-home --system --shell /bin/bash --gid xroad-metrics xroad-metrics || echo "User 'xroad-metrics' not created as it already exists."

# Set Python package permissions
chown root:xroad-metrics /usr/lib/python3/dist-packages/opmon_anonymizer
chmod o-rwx /usr/lib/python3/dist-packages/opmon_anonymizer

# Set bin permissions
chown root:xroad-metrics /usr/bin/xroad-metrics-anonymizer
chmod g-w,g+rx,o-rwx /usr/bin/xroad-metrics-anonymizer


# Set log permissions
chown root:xroad-metrics /var/log/xroad-metrics/anonymizer/logs /var/log/xroad-metrics/anonymizer/heartbeat
chmod g+rwx,o-rwx  /var/log/xroad-metrics/anonymizer/logs /var/log/xroad-metrics/anonymizer/heartbeat

# Set settings file permissions
chown  root:xroad-metrics /etc/xroad-metrics/anonymizer
chmod  g+rwx,o-rwx  /etc/xroad-metrics/anonymizer
chown  root:xroad-metrics /etc/xroad-metrics/anonymizer/settings.yaml
chmod  g+rwx,o-rwx  /etc/xroad-metrics/anonymizer/settings.yaml
