xroad:
  instance: <FILL>

  # X-Road descriptor file that lists all subsystems available.
  # The file is optional and can be used to define localized subsystem names and maintainer e-mail addresses.
  # Refer to documentation on the file format. To use a descriptor file uncomment the setting below.
  # descriptor-path: /etc/xroad-metrics/reports/xroad-descriptor.json

mongodb:
  host: localhost
  user: <FILL>
  password: <FILL>
  # set to True to enable secure connection
  tls:
  # path to CA pem file
  tls-ca-file:

logger:
  name: reports
  module: reports

  # Possible logging levels from least to most verbose are:
  # CRITICAL, FATAL, ERROR, WARNING, INFO, DEBUG
  level: INFO

  # Logs and heartbeat files are stored under these paths.
  # Also configure external log rotation and app monitoring accordingly.
  log-path: /var/log/xroad-metrics/reports/logs
  heartbeat-path: /var/log/xroad-metrics/reports/heartbeat

reports:
  # Generated report pdf-files will be stored in this path
  report-path: /var/lib/xroad-metrics/reports

  # Language translation config files are stored in this path
  translation-path: /etc/xroad-metrics/reports/lang

  # Report template is stored in this path
  html-template:
    dir: /etc/xroad-metrics/reports/template
    file: pdf_report_template.html

  # These CSS files are used to set the report styles
  css-paths:
    - '/etc/xroad-metrics/reports/template/pdf_report_style.css'

  # Report image files are in this path:
  image-path: /etc/xroad-metrics/reports/template/header_images

  # Settings for e-mail notifications about new reports.
  email:
    sender: <FILL>      # e-mail address shown in sender field of notifications
    smtp:
      host: <FILL>
      user: ""          # only needed if SMTP server is using authentication
      password: ""      # only needed if SMTP server is using authentication
      port: 25
      encryption: None  # possible values: None, TLS, STARTTLS
      certfile: ""      # only needed if SMTP server requires TLS client authentication
      keyfile: ""       # only needed if SMTP server requires TLS client authentication

    # Template for the notification e-mail subject
    subject: "X-Road Metrics report for {X_ROAD_INSTANCE}:{MEMBER_CLASS}:{MEMBER_CODE}:{SUBSYSTEM_CODE}"

    # Template for the notification e-mail body.
    # The default template demonstrates all the variables that can be used to generate the notification e-mails.
    message: >
      Dear {EMAIL_NAME},


      There's a new X-Road Metrics report available for an X-Road subsystem where
      you are listed as a contact person.


      Report name: {REPORT_NAME}

      X-Road subsystem: {X_ROAD_INSTANCE}:{MEMBER_CLASS}:{MEMBER_CODE}:{SUBSYSTEM_CODE}

      Report time period: from {START_DATE} to {END_DATE}


      Best regards,

      X-Road Metrics Administration
