version: 2

updates:
  - package-ecosystem: pip
    directories:
      #- "/analysis_module"
      #- "/analysis_ui_module"
      - "/anonymizer_module"
      - "/collector_module"
      - "/corrector_module"
      #- "/opendata_collector_module"
      - "/opendata_module"
      - "/reports_module"
    schedule:
        interval: "weekly"
        day: "thursday"
    groups:
      python-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      python-major:
        applies-to: version-updates
        update-types:
          - "major"
    ignore: # ignoring the following packages as they require python >= 3.9
      - dependency-name: "matplotlib"
        versions:
          - ">= 3.8.0"
      - dependency-name: "pandas"
        versions:
          - ">= 2.1.0"
      - dependency-name: "weasyprint"
        versions:
          - ">= 62.0"
      - dependency-name: "numpy"
        versions:
          - ">= 1.25.0"
      - dependency-name: "contourpy"
        versions:
          - ">= 1.2.0"
      - dependency-name: "markupsafe"
        versions:
          - ">= 3.0.0"
      - dependency-name: "Pillow"
        versions:
          - ">= 11.0"
      - dependency-name: "django"
        versions:
          - ">= 5.0"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "thursday"
    groups:
      actions-update:
        applies-to: version-updates
        patterns:
          - "*"
