---
excludes:
  paths:
  - pattern: "**/test_requirements.txt"
    reason: "TEST_OF"
    comment: "Requirements for testing."
  - pattern: "3RD-PARTY-NOTICES.txt"
    reason: "DOCUMENTATION_OF"
    comment: "3rd party notices."
  - pattern: "**/tests/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."
  - pattern: "**/test_results.html"
    reason: "TEST_OF"
    comment: "This file contains contains test results."

resolutions:
  rule_violations:
    - message: "copyleft-strong license GPL-2.0-or-later in PyPI::jinja2:2.10.1."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The files meant by this license hit are not in use in X-Road-Metrics."

    - message: "copyleft-strong license GPL-3.0-or-later WITH GCC-exception-3.1 in PyPI::scipy:1.10.1."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The exception applies, hence license acquired."

    - message: "copyleft-strong license GPL-3.0-or-later WITH GCC-exception-3.1 in PyPI::numpy:1.24.4."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The exception applies, hence license acquired."

    - message: "copyleft-strong license GPL-3.0-only WITH GCC-exception-3.1 in PyPI::numpy:1.24.4."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "The exception applies, hence license acquired."

    - message: "free-restricted license Bitstream-Vera in PyPI::matplotlib:3.1.2."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Font files that are not modified, hence license acquired."

    - message: "free-restricted license Bitstream-Vera in PyPI::matplotlib:3.1.2."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Font files that are not modified, hence license acquired."
