#! /bin/bash
set -e

# Add users and groups
groupadd xroad-metrics || echo "Group 'xroad-metrics' not created as it already exists."
useradd --create-home --system --shell /bin/bash --gid xroad-metrics xroad-metrics || echo "User 'xroad-metrics' not created as it already exists."

# Set Python package permissions
chown root:xroad-metrics /usr/lib/python3/dist-packages/opmon_corrector
chmod o-rwx /usr/lib/python3/dist-packages/opmon_corrector

# Set bin permissions
chown root:xroad-metrics /usr/bin/xroad-metrics-correctord
chmod g-w,g+rx,o-rwx /usr/bin/xroad-metrics-correctord


# Set log permissions
chown root:xroad-metrics /var/log/xroad-metrics/corrector/logs /var/log/xroad-metrics/corrector/heartbeat
chmod g+rwx,o-rwx  /var/log/xroad-metrics/corrector/logs /var/log/xroad-metrics/corrector/heartbeat

# Set settings file permissions
chown  root:xroad-metrics /etc/xroad-metrics/corrector
chmod  g+rwx,o-rwx  /etc/xroad-metrics/corrector
chown  root:xroad-metrics /etc/xroad-metrics/corrector/settings.yaml
chmod  g+rwx,o-rwx  /etc/xroad-metrics/corrector/settings.yaml
