# Default settings file for X-Road Metrics Analyzer-module.
# Fill in your MongoDB and X-Road configuration.
# 
# To run analyzer for many different X-Road instances, you can create settings
# profiles. For example to have profiles DEV, TEST and PROD copy this file to
# settings_DEV.yaml, settings_TEST.yaml and settings_PROD.yaml.
# Then fill the profile specific settings to each file and use the --profile
# flag when running xroad-metrics-analyzer. For example to run anomaly detection using the TEST profile:
#    xroad-metrics-analyzer --profile TEST find

analyzer:
  corrector-buffer-time: 14400      # minutes
  incident-expiration-time: 14400   # minutes
  training-period:
    length: 3
    unit: MONTHS  # supported options are DAYS, WEEKS or MONTHS

  failed-request-ratio:
    hourly-time-window: yes   # 'yes' to use hourly time window instead of daily for anomaly detection
    threshold: 0.9            # incident reporting threshold as ratio of failed requests in time window

  duplicate-message-ids:
    hourly-time-window: no    # 'yes' to use hourly time window instead of daily for anomaly detection

  time-sync-errors:
    hourly-time-window: yes   # 'yes' to use hourly time window instead of daily for anomaly detection
    thresholds: # relevant fields for monitoring time sync anomalies and the respective minimum value thresholds
      requestNwDuration: -2000
      responseNwDuration: -2000

  historic-averages:
    time-windows:
      hour-weekday: yes   # compare hourly data to historic data from the same weekday and hour
      weekday: yes        # compare daily data to historic data from the same weekday
      hour-monthday: no   # compare hourly data to historic data from same day-of-month and hour
      monthday: no        # compare daily data to historic data from the same day-of-month

    thresholds: # data-fields to monitor and related confidence thresholds
      request_count: 0.95
      mean_request_size: 0.95
      mean_response_size: 0.95
      mean_client_duration: 0.95
      mean_producer_duration: 0.95


xroad:
  instance: <FILL>

mongodb:
  host: localhost
  user: <FILL>
  password: <FILL>

logger:
  name: analyzer
  module: analyzer

  # Possible logging levels from least to most verbose are:
  # CRITICAL, FATAL, ERROR, WARNING, INFO, DEBUG
  level: INFO

  # Logs and heartbeat files are stored under these paths.
  # Also configure external log rotation and app monitoring accordingly.
  log-path: /var/log/xroad-metrics/analyzer/logs
  heartbeat-path: /var/log/xroad-metrics/analyzer/heartbeat
