#! /bin/bash
set -e

# Add users and groups
groupadd xroad-metrics || echo "Group 'xroad-metrics' not created as it already exists."
useradd --create-home --system --shell /bin/bash --gid xroad-metrics xroad-metrics || echo "User 'xroad-metrics' not created as it already exists."

# Set Python package permissions
chown root:xroad-metrics /usr/lib/python3/dist-packages/metrics_opendata_collector
chmod o-rwx /usr/lib/python3/dist-packages/metrics_opendata_collector

# Set bin permissions
chown root:xroad-metrics /usr/bin/xroad-metrics-opendata-collector
chmod g-w,g+rx,o-rwx /usr/bin/xroad-metrics-opendata-collector


# Set log permissions
chown root:xroad-metrics /var/log/xroad-metrics/opendata_collector/logs /var/log/xroad-metrics/opendata_collector/heartbeat
chmod g+rwx,o-rwx  /var/log/xroad-metrics/opendata_collector/logs /var/log/xroad-metrics/opendata_collector/heartbeat

# Set settings file permissions
chown  root:xroad-metrics /etc/xroad-metrics/opendata_collector
chmod  g+rwx,o-rwx  /etc/xroad-metrics/opendata_collector
chown  root:xroad-metrics /etc/xroad-metrics/opendata_collector/settings.yaml
chmod  g+rwx,o-rwx  /etc/xroad-metrics/opendata_collector/settings.yaml

chown  root:xroad-metrics /etc/xroad-metrics/opendata_collector/opendata_sources_settings.yaml
chmod  g+rwx,o-rwx  /etc/xroad-metrics/opendata_collector/opendata_sources_settings.yaml
